### ISSUE TITLE
Not working when directories set in Guardfile and Gemfile symlinked

### ISSUE THREAD

**Issue by deivid-rodriguez** [guard/guard-bundler#29]
As per the title, it doesn't seem to work with the recommended configuration. It only refreshes the bundle if you watch the whole project.

I created an empty project where it can be reproduced. https://github.com/deivid-rodriguez/guard-bundler-bug

Thanks!

**Comment by e2** [comment]
Yeah ... I just removed the bad example from the Readme.

You need to remove the whole `guard :bundler` section from the `Guardfile` and rerun `guard init bundler`. You'll see how the default template is a bit more complex (and handles symlinks better).

The new template tries to be smarter, but I can't make the old template "detect" that there's a new version which you should update. I think there's a Guard issue somewhere for detecting plugin version changes - but that will happen no sooner than Guard 3.x.

Thanks for reporting this - I'm looking for issues I can avoid/fix in Guard 3.x!

**Comment by deivid-rodriguez** [comment]
Thanks to you!
